export enum TodoFilters {
  SHOW_ALL = "SHOW_ALL",
  SHOW_COMPLETED = "SHOW_COMPLETED",
  SHOW_ACTIVE = "SHOW_ACTIVE",
}

export enum Actions {
  ADD,
  TOGGLE,
  DELETE,
  DELETE_COMPLETED,
  UPDATE,
  COMPLETE_ALL,
}
